# Partially taken from https://github.com/ghego/travis_anaconda_jupyter
language: python
python:
  - "3.6"
  - "3.4"
  - "3.5"
install:
  # I don't know how much of this is really necessary. We certainly need
  # Jupyter installed; otherwise, even miniconda may be overkill. -Philip

  - sudo apt-get update
  - sudo apt-get -y install ipython ipython-notebook
  - pip3 install -r requirements.txt
script:
  # If executing the Jupyter notebook conversion doesn't error, then the
  # user should be able to progress through the notebook without error
  - jupyter-nbconvert --execute --to html Start-here.ipynb --ExecutePreprocessor.timeout=300

